# This file is auto-generated by nixos-generate-config during installation.
# It detects your hardware (disks, filesystems, kernel modules, etc.).
#
# To generate this file on a NixOS system:
#   sudo nixos-generate-config --show-hardware-config > hardware-configuration.nix
#
# DO NOT manually edit this file unless you know what you are doing.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Placeholder -- replace with output from nixos-generate-config
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  swapDevices = [ ];

  hardware.enableRedistributableFirmware = true;
}
